export class City{

    cityID = 0;
    cityName = "";
    belongsTo = "";
    history = 0;
    governance = 0;
    reputation = 0;
    space = 0;
    climate = 0;
    georisk = 0;
    geoeconomics = 0;
    gastronomy = 0;
    branding = 0;
    socialActivity = 0;
    expatExp = 0;
    ethics = 0;
    equality = 0;
    humanCap = 0;
    smartcities = 0;
    innovation = 0;
    digitalGovernment = 0;
    education = 0;
    employability = 0;
    connection = 0;
    health = 0;
    sustainability = 0;
    tourism = 0;
    urbanMobility = 0;
    urbanPlanning = 0;
    safety = 0;
    netRealIncome = 0;
    costofLife = 0;
}